# We haven't integrated Travis-ci into our own Github repo,
# but this file is here as a convenience (and probably future
# integration on the official Github)
language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - rbx-2
